### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by prologic** [schollz/kiki#8]
Is there any interest in fixing bugs and adding improvements to this project? See also #5 . Curious to see any level of community around this or usage in the wild. I have a federation setup; but I'm hard pressed to get much usage out of it with friends/family at the moment... (*I'm trying...*).

What's the status of the project? There have been no new commits since over a year go...

**Comment by makew0rld** [comment]
This project is part of schollz's "Github Graveyard". From [this blog post](https://schollz.com/blog/graveyard/):

> I had a lot of fun writing the code, but in the end I realized I wouldn’t use it. To use it would encourage other people to use it and then I’d be stuck with all the problems facing other social networks - how to regulate bad behavior while encouraging openness, etc. I had no desire to write code to regulate content but that what you have to do nowadays if you have a social network.

I would recommend checking out [Scuttlebutt](https://scuttlebutt.nz/) instead.
